Marines
awt-02/pivotal-api pull request #6
Opened 2019-03-31 23:33 UTC by 88mary256

2019-04-01 20:20 UTC, d4vidmc requested changes

2019-04-01 20:20 UTC, d4vidmc commented on config.yml
> + token: "290548f427d7f7d10b461e95036ea3a3"
delete this

2019-04-01 20:20 UTC, d4vidmc commented on config.yml
> + logger_path: "\\resources\\logs"
change to \log

2019-04-01 20:20 UTC, d4vidmc commented on features/epics.feature
> +    When I get all epics of project with id 2322921
do not hardcode the id of an epic

2019-04-01 20:20 UTC, d4vidmc commented on features/epics.feature
> +    When I get all epics of project with id 2322921 and filter {state:unstarted}
Do not hardcode the project id

2019-04-01 20:20 UTC, d4vidmc commented on features/epics.feature
> +    When I get epic with id 164996934 from project 2322921
Do not hardcode the id of the project and epic

2019-04-01 20:20 UTC, d4vidmc commented on features/steps/epics_steps.py
> +    pprint.pprint(epics)
use logger instead of print statement

2019-04-01 20:20 UTC, d4vidmc commented on features/steps/epics_steps.py
> +    expect(epic) != ""
where are the error messages

2019-04-01 20:20 UTC, d4vidmc commented on features/steps/project_steps.py
> +#from pip import logger
remove this

2019-04-01 20:20 UTC, d4vidmc commented on features/steps/project_steps.py
> +#    logger.info(u'STEP: Given I make a connection')
remove commented lines

2019-04-01 20:20 UTC, d4vidmc commented on features/steps/project_steps.py
> +    print("x")
remove print

2019-04-01 20:20 UTC, d4vidmc commented on src/data/epic.py
> +        self.description = None  # string
Use dictionary template for epic variables

2019-04-01 20:20 UTC, d4vidmc commented on src/data/epic.py
> +            body = body + "\"name\":\"" + self.name + "\","
refactor this code

2019-04-01 20:20 UTC, d4vidmc commented on src/pivotal_services/base_service.py
> +        # self.property_reader =
remove commented code

2019-04-01 20:20 UTC, d4vidmc commented on src/pivotal_services/epic_service.py
> +        self.base_url = "https://www.pivotaltracker.com/services/v5"
use config

2019-04-01 20:20 UTC, d4vidmc commented on src/pivotal_services/epic_service.py
> +        # "https://www.pivotaltracker.com/services/v5/projects/$PROJECT_ID/epics?fields=id%2Ccomments"
remove this

2019-04-01 20:20 UTC, d4vidmc commented on src/pivotal_services/epic_service.py
> +        return self.request_handler.post_request(url, epic)
change to
return self.request_handler.post_request(url, epic.get_body() if  isinstance(epic, Epic) else epic)

2019-04-01 20:20 UTC, d4vidmc commented on src/tests/epic_service_tests.py
> +epic_id=4275384
delete hardcoded variables

2019-04-01 20:20 UTC, d4vidmc commented on src/pivotal_services/epic_service.py
> +            return self.request_handler.put_request(url, epic.getBody())
use ternary condition

2019-04-02 19:29 UTC, merged

2019-04-15 12:55 UTC, Fergitgirl commented on config.yml
> + token: "290548f427d7f7d10b461e95036ea3a3"
please delete token